import { Inter } from 'next/font/google'
import '.././globals.css'
import NavBar from '@/components/NavBar'
import { AuthProvider } from '@/context/AuthContext'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { LeftSidBar } from '@/components/LeftSidBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Reddit Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ToastContainer position='bottom-right' theme='dark'/>
          <NavBar />
          <main className='flex flex-row'>
            <LeftSidBar />
            <section className='main-container'>
              <div className='w-full max-w-4xl'>{children}</div>
            </section>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
